name: SmallRye Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: actions/setup-java@v4
        name: set up jdk ${{matrix.java}}
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn -B formatter:validate install --file pom.xml

      - uses: actions/checkout@v4
        name: checkout smallrye-config
        with:
          repository: smallrye/smallrye-config
          path: smallrye-config

      - name: test with smallrye-config
        run: |
          cd smallrye-config
          mvn versions:update-property -Dproperty=version.smallrye.testing -DallowSnapshots=true -N
          git diff pom.xml
          mvn install

  quality:
    needs: [build]
    if: github.event_name == 'push' && startsWith('smallrye', github.repository)
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with docs and coverage
        run: mvn verify -Pcoverage javadoc:javadoc

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: sonar
        run: mvn sonar:sonar -Dsonar.projectKey=smallrye_smallrye-testing -Dsonar.token=${{secrets.SONAR_TOKEN}}
